### ISSUE TITLE
astring fails to build with 4.14.0+trunk ocaml

### ISSUE THREAD

**Issue by shubhamkumar13** [dbuenzli/astring#20]
I get the following error log when I try to build `astring`  with `4.14.0+trunk`  and `dune.2.9.0`
```
#=== ERROR while compiling astring.0.8.5 ======================================#
# context     2.0.8 | linux/x86_64 | ocaml-variants.4.14.0+trunk | https://opam.ocaml.org#1fc79772
# path        ~/.opam/4.14.0+trunk/.opam-switch/build/astring.0.8.5
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build --pinned false
# exit-code   1
# env-file    ~/.opam/log/astring-2323604-d2c37b.env
# output-file ~/.opam/log/astring-2323604-d2c37b.out
### output ###
# 6 | let () = ignore (Toploop.use_file Format.err_formatter "astring_top_init.ml")
# [...]
# Error: Unbound value Toploop.use_file
# Command exited with code 2.
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
#      'README.md' 'src/astring.a' 'src/astring.cmxs' 'src/astring.cmxa'
#      'src/astring.cma' 'src/astring.cmx' 'src/astring.cmi' 'src/astring.mli'
#      'src/astring_string.cmx' 'src/astring_sub.cmx' 'src/astring_char.cmx'
#      'src/astring_escape.cmx' 'src/astring_base.cmx' 'src/astring_unsafe.cmx'
#      'src/astring_top.a' 'src/astring_top.cmxs' 'src/astring_top.cmxa'
#      'src/astring_top.cma' 'src/astring_top.cmx' 'src/astring_top_init.ml'
#      'test/examples.ml']: exited with 10

```

**Comment by dbuenzli** [comment]
See https://github.com/ocaml/ocaml/issues/10556
